# 开发环境下配置
spring:
  # 数据源
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/plms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: zhongjing
      driver-class-name: com.mysql.cj.jdbc.Driver