# 生产环境下配置

spring:
  # 数据源
  datasource:
    druid:
      url: jdbc:mysql://172.16.43.8:3306/plms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: zhongjing
      password: zhongjing0121
      driver-class-name: com.mysql.cj.jdbc.Driver
